apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "service.name" . }}-init
data:
  NODE_ENV: {{ .Values.nodeEnv }}
  VAULT_ADDR: http://active.vault.service.consul:8200
  VAULT_K8S_AUTH_PATH:  {{ .Values.initContainer.k8sAuthPath }}
  SECRETS_FILEPATH: {{ .Values.vault.volumes.initConfig.initConfigMountPath }}/{{ .Values.vault.secretPathFilename }}
  {{- $files := .Files }}
  secretsPath: |-
{{ $files.Get .Values.vault.secretPathFilename  | indent 4}}